name 'oh_my_zsh'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures oh_my_zsh'
long_description 'Installs/Configures oh_my_zsh'
version '0.1.0'
chef_version '>= 14.0'

depends 'git'
depends 'zsh'
